openapi: 3.0.3
info:
  title: WASAPhoto
  description: |
    This is an API of an app/web page that allows the user to keep in touch with their friends by sharing, liking and commenting photos of special moments.
  version: 1.0.0
  
components:
  schemas:
    userProfile:
      title: User profile
      description: This represents a single user profile.
      type: object
      properties:
        photos:
          description: User's photos IDs.
          type: array
          items: { $ref: "#/components/schemas/image" }
          minItems: 0
          maxItems: 10000
        numberOfPhotos:
          description: Number of photos posted
          type: integer
          example: 45
        followers:
          description: List of followers.
          type: array
          items: { $ref: "#/components/schemas/username" }
          minItems: 0
          maxItems: 10000
        following:
          description: List of following users.
          type: array
          items: { $ref: "#/components/schemas/username" }
          minItems: 0
          maxItems: 10000
    userPost:
      title: User post
      description: This represents a sigle user post.
      type: object
      properties:          
        photo: { $ref: "#/components/schemas/image" }
        dateAndTime:
          description: Date and time on which the photo was posted.
          type: string
          format: date-time
          minLength: 20
          maxLength: 20
          example: "2021-01-30T08:30:00Z"
        likes:
          description: Number of likes
          type: integer
          example: 56
        comments:
          description: Number of comments
          type: integer
          example: 28
    username:
      title: Username
      description: Username that everyone can see
      type: string
      pattern: "^[a-zA-Z0-9]*$"
      minLength: 3
      maxLength: 16
      example: Alice68
    ID:
      title: Generic ID
      description: Unique identifier
      type: string
      pattern: "^[a-zA-Z0-9]*$"
      minLength: 10
      maxLength: 10
      readOnly: true
    image:
      title: Raw image
      description: ID of photo
      type: string
      pattern: "^[a-zA-Z0-9]*$"
      minLength: 10
      maxLength: 10
      readOnly: true
  responses:
    NoContent: 
      description: "Operation successful; no response body needed."
    BadRequest:
      description: The username cannot be used.
    UnauthorizedError:
      description: Access token is missing or invalid
    NotFound:
      description: The server cannot find the requested resource.
  parameters:
    userID:
      name: userID
      in: path
      description: Unique user identifier
      schema: { $ref: "#/components/schemas/ID"}
      example: US1e234567
      required: true
    photoID:
      name: photoID
      in: path
      description: Unique photo identifier
      schema: { $ref: "#/components/schemas/ID"}
      example: PH12e34567
      required: true
    commentID:
      name: commentID
      in: path
      description: Unique comment identifier
      schema: { $ref: "#/components/schemas/ID"}
      example: CM123e4567
      required: true
    followedID:
      name: followedID
      in: path
      description: Unique followed user identifier
      schema: { $ref: "#/components/schemas/ID"}
      example: FW1234e567
      required: true
    bannedID:
      name: bannedID
      in: path
      description: Unique banned user identifier
      schema: { $ref: "#/components/schemas/ID"}
      example: BN12345e67
      required: true
    likeID:
      name: likeID
      in: path
      description: Unique like identifier
      schema: { $ref: "#/components/schemas/ID"}
      example: LK123456e7
      required: true
  securitySchemes:
    bearerAuth:
      description: Bearer authentication scheme
      type: http
      scheme: bearer

security:
  - bearerAuth: []
  
tags:
  - name: "Login"
    description: Functions for logging in
  - name: "Profile"
    description: Functions for updating the profile
  - name: "Stream"
    description: Functions for the stream of photos
  - name: "Following"
    description: Functions for the "following" list
  - name: "Ban"
    description: Functions for the "banned" list
  - name: "Photo"
    description: Functions for updating info about a photo
    
paths:
  /session:
    post:
      tags: ["Login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              description: Object containing the username of the user that wants to log in 
              type: object
              properties:
                name:
                  description: Username
                  type: string
                  example: Maria
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                description: Object containing the user's identifier
                type: object
                properties:
                  identifier:
                    description: User identifier
                    type: string
                    pattern: "^[a-zA-Z0-9]*$"
                    minLength: 12
                    maxLength: 12
                    example: "abcdef012345"
        '401': { $ref: '#/components/responses/UnauthorizedError' }
  
  /users/:
    summary: List of users
    description: This is the list (resource) of all users.
    get:
      tags: ["Profile"]
      summary: Gets user's profile
      description: |-
        If the user exists, it returns the profile; otherwise it returns an error.
      operationId: getUserProfile
      parameters: 
        - name: username
          in: query
          description: This is the username of the user whose profile we want to see.
          required: true
          schema: { $ref: "#/components/schemas/username" }
      responses:
        '200': 
          description: The resource has been fetched and transmitted in the message body.
          content:
            application/json:
              schema: { $ref: "#/components/schemas/userProfile" }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
        '404': { $ref: '#/components/responses/NotFound' }
  
  /users/{userID}:
    parameters:
      - $ref: "#/components/parameters/userID"
    put:
      tags: ["Profile"]
      summary: Updates username
      description: |-
        If the username is available it uploads the old one; otherwise it notifies the user that the username is already used.
      operationId: setMyUserName
      requestBody:
        description: New username to replace the old one.
        content:
          application/json:
            schema: { $ref: "#/components/schemas/username" }
        required: true
      responses:
        '204': { $ref: '#/components/responses/NoContent' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
    get:
      tags: ["Stream"]
      summary: Gets user's stream.
      description: |-
        It returns a stream with following users' photos and respective information in reverse chronological order.
      operationId: getMyStream
      responses:
        '200':
          description: The request succeeded and the current stream is in response body.
          content:
            application/json:
              schema:
                description: Array of user posts
                type: array
                items: { $ref: "#/components/schemas/userPost"}
                minItems: 1
                maxItems: 50
        '401': { $ref: '#/components/responses/UnauthorizedError' }
    
  /users/{userID}/following/{followedID}:
    parameters:
      - $ref: "#/components/parameters/userID" 
      - $ref: "#/components/parameters/followedID"
    put:
      tags: ["Following"]
      summary: Follows user
      description: Adds user to following list
      operationId: followUser
      responses:
        '201':
          description: User followed successfully.
          content:
            application/json:
              schema: { $ref : "#/components/schemas/ID"}
        '401': { $ref: '#/components/responses/UnauthorizedError' }
        '404': { $ref: '#/components/responses/NotFound' } 
    delete:
      tags: ["Following"]
      summary: Unfollows user
      description: Removes user from following list
      operationId: unfollowUser
      responses:
        '204': { $ref: '#/components/responses/NoContent' }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
  
  /users/{userID}/ban/{bannedID}:
    parameters:
      - $ref: "#/components/parameters/userID"
      - $ref: "#/components/parameters/bannedID"
    put:
      tags: ["Ban"]
      summary: Bans user
      description: Adds user to banned list
      operationId: banUser
      responses:
        '201':
          description: User banned successfully.
          content:
            application/json:
              schema: { $ref : "#/components/schemas/ID"}
        '401': { $ref: '#/components/responses/UnauthorizedError' }
        '404': { $ref: '#/components/responses/NotFound' }
    delete:
      tags: ["Ban"]
      summary: Unbans user
      description: Removes user from banned list
      operationId: unbanUser
      responses:
        '204': { $ref: '#/components/responses/NoContent' }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
  
  /users/{userID}/photos/:
    parameters:
      - $ref: "#/components/parameters/userID"
    post:
      tags: ["Profile"]
      summary: Uploads a photo
      description: Uploads the photo send in the request body.
      operationId: uploadPhoto
      requestBody:
        description: The photo to upload on profile.
        content:
          image/png: 
            schema:
              description: File to be uploaded
              type: string
              format: binary
      responses:
        '201':
          description: Photo uploaded successfully.
          content:
            application/json:
              schema: { $ref : "#/components/schemas/ID"}
        '401': { $ref: '#/components/responses/UnauthorizedError' }
    
  /users/{userID}/photos/{photoID}:
    parameters:
      - $ref: "#/components/parameters/userID"
      - $ref: "#/components/parameters/photoID"
    delete:
      tags: ["Profile"]
      summary: Deletes a photo
      description: Deletes the photo from user's profile.
      operationId: deletePhoto
      responses:
        '204': { $ref: '#/components/responses/NoContent' }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
    
  /photos/{photoID}:
    parameters:
      - $ref: "#/components/parameters/photoID"
    get:
      tags: ["Photo"]
      summary: Gets the raw image
      description: Returns the image requested
      responses:
        '200':
          description: Requested image
          content:
            image/png:
              schema:
                description: Raw image
                type: string
                format: binary

  /photos/{photoID}/comments:
    parameters:
      - $ref: "#/components/parameters/photoID"
    post:
      tags: ["Photo"]
      summary: Adds a comment
      description: Adds a comment to photo.
      operationId: commentPhoto
      requestBody:
        description: Content of the comment.
        content:
          application/json:
            schema:
              description: Object containing username and comment of the person that commented
              type: object
              properties:
                username: { $ref: '#/components/schemas/username' }
                comment:
                  description: Comment to be uploaded
                  type: string
                  pattern: "^.*?$"
                  minLength: 1
                  maxLength: 300
                  example: "Nice pic!"
      responses:
        '201': 
          description: Comment uploaded successfully.
          content:
            application/json:
              schema: { $ref : "#/components/schemas/ID"}
        '401': { $ref: '#/components/responses/UnauthorizedError' }
    
  /photos/{photoID}/comments/{commentID}:
    parameters:
      - $ref: "#/components/parameters/photoID"
      - $ref: "#/components/parameters/commentID"
    delete:
      tags: ["Photo"]
      summary: Deletes a comment
      description: Removes a comment from photo.
      operationId: uncommentPhoto
      responses:
        '204': { $ref: '#/components/responses/NoContent' }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
  
  /photos/{photoID}/likes/{likeID}:
    parameters:
      - $ref: "#/components/parameters/photoID"
      - $ref: "#/components/parameters/likeID"
    put:
      tags: ["Photo"]
      summary: Adds a like to a photo
      description: Adds a like to the photo
      operationId: likePhoto
      responses:
        '201':
          description: User banned successfully.
          content:
            application/json:
              schema: { $ref : "#/components/schemas/ID"}
        '401': { $ref: '#/components/responses/UnauthorizedError' }
    delete:
      tags: ["Photo"]
      summary: Removes a like
      description: Removes a like from photo
      operationId: unlikePhoto
      responses:
        '204': { $ref: '#/components/responses/NoContent' }
        '401': { $ref: '#/components/responses/UnauthorizedError' } 
